# Generated by Django 6.0.2 on 2026-02-16 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='startups/')),
                ('description', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('founder', models.CharField(max_length=255)),
                ('founded_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('stage', models.CharField(choices=[('Seed', 'Seed'), ('Series A', 'Series A'), ('Series B', 'Series B'), ('Series C', 'Series C'), ('IPO', 'IPO')], max_length=20)),
                ('equity_percentage', models.DecimalField(decimal_places=2, help_text='Equity percentage owned', max_digits=5)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='core.startup')),
            ],
        ),
    ]
