# Generated by Django 5.0.2 on 2026-02-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='compact_view',
            field=models.BooleanField(default=False, help_text='Use compact view'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_format',
            field=models.CharField(default='mdy', help_text='Date format preference', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_charts',
            field=models.BooleanField(default=True, help_text='Show charts and graphs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Two-factor authentication enabled'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_secret',
            field=models.CharField(blank=True, help_text='2FA secret key', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(default='usd', help_text='Preferred currency', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='utc', help_text='Preferred timezone', max_length=50),
        ),
    ]
