# Generated by Django 5.0.2 on 2026-02-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_compact_view_userprofile_date_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Subscriber email address', max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Subscription status')),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(default='USD', help_text='Preferred currency', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_visibility',
            field=models.CharField(default='public', help_text='Profile visibility', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Preferred timezone', max_length=50),
        ),
    ]
