# Generated by Django 5.0.2 on 2026-02-17 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_investments', models.BooleanField(default=True, help_text='New investment opportunities')),
                ('email_startups', models.BooleanField(default=True, help_text='Startup updates and milestones')),
                ('email_market', models.BooleanField(default=False, help_text='Market trends and analysis')),
                ('email_weekly', models.BooleanField(default=True, help_text='Weekly portfolio summary')),
                ('push_watchlist', models.BooleanField(default=True, help_text='Watchlist updates')),
                ('push_messages', models.BooleanField(default=True, help_text='Messages and alerts')),
                ('language', models.CharField(default='en', help_text='Preferred language', max_length=10)),
                ('timezone', models.CharField(default='UTC', help_text='Preferred timezone', max_length=50)),
                ('currency', models.CharField(default='USD', help_text='Preferred currency', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
